SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE `ESPtable2` (
  `ID` int(5) NOT NULL,
  `ANGLE` int(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `ESPtable2` (`ID`, `ANGLE`) VALUES
(99999, 0);

ALTER TABLE `ESPtable2`
  ADD PRIMARY KEY (`ID`);
